load("@fbsource//tools/build_defs:default_platform_defs.bzl", "ANDROID", "APPLE", "CXX", "FBCODE", "WINDOWS")
load("@fbsource//tools/build_defs:fb_native_wrapper.bzl", "fb_native")
load("@fbsource//tools/build_defs:fb_xplat_rust_library.bzl", "fb_xplat_rust_library")
load("@fbsource//tools/build_defs:fb_xplat_suffixed_aliases.bzl", "create_forwarding_aliases")
load("@fbsource//tools/build_defs:fbsource_utils.bzl", "is_fbcode_compatible", "is_fbcode_mode_mac", "is_fbcode_mode_win", "is_xplat")

oncall("rust_libraries")

# Avoid duplicate symbols by redirecting the top-level iobuf/iobuf-ffi targets to only one variant
# of the library. This way, we don't end up with both `fbcode//folly/rust/iobuf:iobuf` and `fbsource//xplat/folly/rust/iobuf:iobuf`
# in the same build graph.
create_forwarding_aliases(
    name = "iobuf",
    actual_name = select({
        "DEFAULT": "fbsource//xplat/folly/rust/iobuf:_iobuf",
        "ovr_config//os:linux": "fbcode//folly/rust/iobuf:_iobuf" if is_fbcode_compatible() else "fbsource//xplat/folly/rust/iobuf:_iobuf",
        "ovr_config//os:macos": "fbcode//folly/rust/iobuf:_iobuf" if is_fbcode_mode_mac() else "fbsource//xplat/folly/rust/iobuf:_iobuf",
        "ovr_config//os:windows": "fbcode//folly/rust/iobuf:_iobuf" if is_fbcode_mode_win() else "fbsource//xplat/folly/rust/iobuf:_iobuf",
    }),
    platforms = (CXX, ANDROID, APPLE, FBCODE, WINDOWS),
    visibility = ["PUBLIC"],
) if is_xplat() else None


fb_xplat_rust_library(
    name = "_iobuf",
    srcs = glob(["src/*.rs"]),
    crate = "iobuf",
    crate_root = "src/lib.rs",
    cxx_bridge = "src/lib.rs",
    platforms = (CXX, ANDROID, APPLE, WINDOWS),
    test_deps = [
        "fbsource//third-party/rust:quickcheck",
        "fbsource//xplat/thrift/lib/rust/src/dep_tests:test_if-rust",
    ],
    xplat_preexisting_target_flavors = [FBCODE],
    deps = [
        "fbcode//eden/scm/lib/minibytes:minibytes",
        "fbsource//third-party/rust:bytes",
        "fbsource//third-party/rust:cxx",
        "fbsource//third-party/rust:memmap2",
        "fbsource//xplat/thrift/lib/rust:fbthrift",
        "//folly/rust/iobuf-sys:iobuf-sys",
        "//thrift/lib/rust:fbthrift",
    ],
)

fb_native.alias(
    name = "_iobufFbcode",
    actual = ":_iobuf",
    visibility = ["PUBLIC"],
) if is_xplat() else None
